### ISSUE TITLE
When editing an event, the 'host' name doesn't appear 

### ISSUE THREAD

**Issue by margulies** [sparkletown/sparkle#1054] opened 2020-12-22 11:15 UTC
The 'host' name doesn't appear when editing an event, and needs to be entered again each time. I was able to correct this by adding:

`host: event.host,`

to: 

https://github.com/sparkletown/sparkle/blob/f34d7bdec3a928e6afcaad91eccfedcf8f211968/src/pages/Admin/AdminEventModal.tsx#L81-L86

(I figured it was easier to post an issue on this that submitting a PR, but let me know what you prefer)

**Comment by 0xdevalias** [comment] 2021-02-12 08:47
Thanks for raising this issue @margulies, sorry for the super slow reply-time!

Assuming we don't end up running into CI issues trying to get things merged again (which I believe I may have resolved last time, but haven't actually tested that yet), then I think in general, opening a PR is probably more helpful for us. That way we don't need to 'context switch' too much from the feature we're working on, and it could be as simple as just reviewing the code and clicking accept.

I think that's one of the reasons this has taken me so long to get back to reply to, 🧠  has just been so deep in other features/code cleanup that it keeps slipping my mind.

We've got this issue on our sprint board at the moment, so it's on our radar! 

---

FYI @sparkletown/engineering I believe https://github.com/sparkletown/internal-sparkle-issues/issues/74 is a duplicate of this issue, and includes a few more technical details as well.

Since we also have the beta `admin_v2` code as well now, this bug might exist there too; so it he fix might require changes in 2 spots.

**Comment by mobilevinay** [comment] 2021-02-14 10:28
@malaikaaiyar can you confirm if this bug us happening on staging?

**Comment by malaikaaiyar** [comment] 2021-02-15 16:54
Can't confirm admin things until I get admin access

**Comment by 0xdevalias** [comment] 2021-02-16 07:20
> Can't confirm admin things until I get admin access

@malaikaaiyar See thread in https://doesitsparkle.slack.com/archives/C01ER4M61TL/p1613459503109000

**Comment by malaikaaiyar** [comment] 2021-02-16 10:20
This is still happening on staging. I created an event with my name, and then when I edit it it looks like this: 
![Screen Shot 2021-02-16 at 10 20 06 AM](https://user-images.githubusercontent.com/51083763/108049751-95e59100-7040-11eb-8361-17bd9b25d98b.png)

**Comment by margulies** [comment] 2021-02-16 11:52
Just wanted to mention that I managed to fix this is the most recent codebase using the addition mentioned at the top (adding: `host: event.host,` to `sparkle/src/pages/Admin/AdminEventModal.tsx`). 

Also, in `admin_v2`, I haven't yet figured out how to edit events that were already created, so at the moment this doesn't appear to be an issue there.

**Comment by malaikaaiyar** [comment] 2021-02-16 12:19
So, it's not been deployed right? Can you make a PR?

**Comment by margulies** [comment] 2021-02-16 12:51
Just made a PR with the fix (1182)

**Comment by 0xdevalias** [comment] 2021-02-17 05:05
> Also, in `admin_v2`, I haven't yet figured out how to edit events that were already created, so at the moment this doesn't appear to be an issue there.

@margulies To my knowledge that feature doesn't exist in admin v2 yet. I've created https://github.com/sparkletown/internal-sparkle-issues/issues/400  to track this.

---

> Just made a PR with the fix (#1182)

@margulies Amazing, thankyou! :)

**Closed** 2021-02-17 09:54 UTC
Labels: P2 - High, 🐛 bug

**Comment by 0xdevalias** [comment] 2021-02-18 11:06
Thanks again for raising this bug + the PR to fix it @margulies :)
